version: '3'

services:
  proxy:
    image: coinietrade-proxy:$TAG
    build: .
    ports:
      - "8080:80"
    environment:
      - NGINX_WORKERS=1
      - PORT=80
      - HEROKU_APP_HOST=localhost:8080
      - HEROKU_APP_DOMAIN=coinietradefront_web_1:5000
      - MAINT_FLAG=false
    external_links:
      - coinietradefront_web_1

networks:
  default:
    external:
      name: coinietradefront_default
