version: '3'

services:
  proxy:
    image: coinietrade-proxy:$TAG
    container_name: proxy
    build: .
    ports:
      - "8080:80"
    environment:
      - NGINX_WORKERS=1
      - PORT=80
      - HEROKU_APP_HOST=localhost:8080
      - HEROKU_APP_DOMAIN=web-ci:5000
      - MAINT_FLAG=false
    external_links:
      - web-ci

networks:
  default:
    external:
      name: coinietrade-front_default
